name: ng2gen
version: 0.1.0
description: Angular2 Component Files Generator
author:
  - Luis Vargas <luisvargastijerino@gmail.com>
  - Hadrien Lejard <hadrien.lejard@gmail.com>
homepage: https://github.com/luisvt/ng2gen
environment:
  sdk: ">=1.8.0 <2.0.0"

dependencies:
  dev_string_converter: ^0.1.0
  yaml: "^2.1.9"
  dart_style: "^0.2.2"

executables:
  ng2gen: main
