project:
  root: "app.dart"
  components: "components"
  directives: "directives"
  services: "services"
  routes: "routes"
  pipes: "pipes"
  sass: false
  less: false

server:
  hostname: "0.0.0.0"
  port: 1337