project:
  name: "__projectName__"
  components: "lib/components"
  directives: "lib/directives"
  services: "lib/services"
  routes: "lib/components"
  pipes: "lib/pipes"

server:
  hostname: "0.0.0.0"
  port: 1337