name: __projectName__
version: 0.0.1
description:
author:
homepage:

dependencies:
  angular2: 2.0.0-beta.17
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1

dev_dependencies:
  grinder: ^0.8.0+2
  test: ^0.12.13+1
  watcher: ^0.9.7+2
  yaml: ^2.1.9
  ng2gen: ^0.1.0

transformers:
  - angular2:
      entry_points: web/main.dart
  - dart_to_js_script_rewriter
  - $dart2js:
      minify: true
      commandLineOptions:
          - --trust-type-annotations
          - --trust-primitives
